# Generated by Django 3.2.8 on 2023-07-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0002_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
