# Generated by Django 3.2.8 on 2022-07-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0004_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='business_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Salon.businessactivity'),
            preserve_default=False,
        ),
    ]
