# Generated by Django 3.2.8 on 2023-07-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0004_alter_businessactivity_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivity',
            name='apartment_number',
            field=models.CharField(default='', max_length=45, null=True),
        ),
    ]
