# Generated by Django 3.2.8 on 2022-07-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0007_rename_specialization_employeespecialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessactivity',
            name='city',
            field=models.CharField(default='Wejherowo', max_length=200),
            preserve_default=False,
        ),
    ]
