# Generated by Django 3.2.8 on 2022-07-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0008_businessactivity_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeespecialization',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='spec',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Salon.employeespecialization'),
            preserve_default=False,
        ),
    ]
