# Generated by Django 3.2.8 on 2022-09-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0013_auto_20220911_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeimage',
            name='content',
        ),
    ]
