# Generated by Django 3.2.8 on 2022-10-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0016_remove_employeeimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeserviceconfiguration',
            name='employee_image',
        ),
        migrations.CreateModel(
            name='EmployeeImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon.employeeimage')),
            ],
        ),
        migrations.AddField(
            model_name='employeeserviceconfiguration',
            name='image_set_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Salon.employeeimageset'),
        ),
    ]
