# Generated by Django 3.2.8 on 2022-10-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0018_auto_20221018_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeimageset',
            name='image',
        ),
        migrations.AddField(
            model_name='employeeimage',
            name='image_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Salon.employeeimageset'),
        ),
    ]
