# Generated by Django 3.2.8 on 2022-10-19 14:10

import Salon.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0019_auto_20221018_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(blank=True, null=True, upload_to=Salon.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ClientEmployeeRelation',
        ),
        migrations.AddField(
            model_name='employee',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Salon.employeeavatar'),
        ),
    ]
