# Generated by Django 3.2.8 on 2022-12-14 08:08

import Salon.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0026_auto_20221113_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(blank=True, null=True, upload_to=Salon.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('BusinessActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon.businessactivity')),
            ],
        ),
    ]
