# Generated by Django 3.2.8 on 2022-12-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0027_businessactivityimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessactivityimage',
            old_name='BusinessActivity',
            new_name='business_activity',
        ),
    ]
