# Generated by Django 3.2.8 on 2023-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0032_auto_20230418_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
