# Generated by Django 3.2.8 on 2022-07-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0009_auto_20220730_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='employee',
        ),
    ]
