# Generated by Django 3.2.8 on 2022-07-30 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0010_remove_service_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeServiceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salon.service')),
            ],
        ),
    ]
