# Generated by Django 3.2.8 on 2022-09-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0012_auto_20220820_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='employee',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Salon.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeeserviceconfiguration',
            name='employee_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Salon.employeeimage'),
        ),
    ]
