# Generated by Django 3.2.8 on 2022-09-11 12:36

import Salon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0014_remove_employeeimage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeimage',
            name='content',
            field=models.ImageField(blank=True, null=True, upload_to=Salon.models.upload_path),
        ),
    ]
