# Generated by Django 3.2.8 on 2022-09-11 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0015_employeeimage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeimage',
            name='name',
        ),
    ]
