# Generated by Django 3.2.8 on 2022-10-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0017_auto_20221018_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeimageset',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='employeeserviceconfiguration',
            old_name='image_set_id',
            new_name='image_set',
        ),
    ]
