# Generated by Django 3.2.8 on 2022-10-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0021_servicecategory_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeserviceconfiguration',
            name='display_order',
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
