# Generated by Django 3.2.8 on 2022-10-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0022_auto_20221020_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['display_order']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='avatar',
        ),
        migrations.AddField(
            model_name='employeeavatar',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Salon.employee'),
            preserve_default=False,
        ),
    ]
