# Generated by Django 3.2.8 on 2022-12-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0028_rename_businessactivity_businessactivityimage_business_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessactivity',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
