# Generated by Django 3.2.8 on 2023-04-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0030_employeeavailability_employeeavailabilityconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeavailability',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
