# Generated by Django 3.2.8 on 2023-04-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0031_alter_employeeavailability_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeavailability',
            name='end_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeeavailability',
            name='start_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
