# Generated by Django 3.2.8 on 2023-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0035_businessactivity_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessactivity',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
