# Generated by Django 3.2.8 on 2023-07-05 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0036_alter_businessactivity_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticprocedure',
            name='non_user_client',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cosmeticprocedure',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Salon.user'),
        ),
        migrations.DeleteModel(
            name='AppointmentHistory',
        ),
    ]
